// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/home/lyw/work-space/cscec-antd/node_modules/dumi/theme-default/slots/ContentFooter/index.js';
