// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as tab0 from '/home/lyw/work-space/cscec-antd/docs/components/date-picker/index.$tab-design.zh-CN.md';

export const tabs = {
  'docs/components/date-picker/index.$tab-design.zh-CN': { key: 'design', title: '', titleIntlId: '', components: tab0 },
}
