export const seedToken = {
  blue: '#008ee0',
  green: '#29bc38',
  gold: '#ff9933',
  red: '#f60a14',
  colorPrimary: '#008ee0',
  colorInfo: '#008ee0',
  colorSuccess: '#29bc38',
  colorWarning: '#ff9933',
  colorError: '#ff3333',
};

export const mapToken = {
  colorText: 'rgba(0, 0, 0, 0.85)',
  colorBorderSecondary: '#e8e8e8',
  colorFillSecondary: 'rgba(0, 0, 0, 0.09)',

  borderRadius: 4,
  borderRadiusXS: 4,
  borderRadiusLG: 4,
  borderRadiusSM: 4,
  fontSizeHeading2: 28,
  fontSizeHeading1: 36,
  lineHeightHeading1: '1.3888888888888888888888',
  lineHeightHeading2: '1.357142857142857',
};

/**
 * 组件主题
 * @type {import('./index').ThemeConfig['components']}
 */
export const ComponentsToken = {
  Button: {
    controlOutline: 'rgba(0, 142, 224, 0.09)',
    colorErrorOutline: 'rgba(255, 51, 51, 0.09)',
    controlTmpOutline: 'rgba(191, 191, 191, 0.09)',
    controlHeightLG: 36,
  },
  Anchor: {
    linkPaddingBlock: 8,
    linkPaddingInlineStart: 12,
  },
  Breadcrumb: {
    itemColor: 'rgba(0, 0, 0, 0.25)',
    lastItemColor: 'rgba(0, 0, 0, 0.65)',
    linkColor: 'rgba(0, 0, 0, 0.25)',
    separatorColor: 'rgba(0, 0, 0, 0.25)',
    linkHoverColor: ' #008EE0',
    colorBgTextHover: '#FFFFFF',
    colorText: 'rgba(0, 0, 0, 0.65)',
    colorTextDescription: 'rgba(0, 0, 0, 0.25)',
  },
  Dropdown: {
    paddingXXS: 2,
    marginXXS: 2,
    marginXS: 6,
    paddingXS: 4,
  },
  Pagination: {
    itemActiveBg: '#008EE0',
    colorPrimary: '#ffffff',
    colorBgTextHover: 'rgb(255, 255, 255)',
    colorPrimaryHover: 'rgb(255, 255, 255)',
  },
  Steps: {
    colorFillContent: 'rgba(0, 0, 0, 0.04)',
    controlItemBgActive: 'rgba(0, 142, 224, 0.09)',
    dotSize: 6,
    dotCurrentSize: 8,
    fontSize: 14,
    titleLineHeight: 28,
  },
  Cascader: { menuPadding: 0, borderRadiusSM: 0 },
  Checkbox: {},
  DatePicker: {},
  Form: {},
  Input: {},
  InputNumber: {},
  Mentions: {},
  Radio: {},
  Rate: {},
  Select: {
    controlItemBgActive: ' rgba(0,142,224,0.1)',
    controlItemBgHover: 'rgba(38,171,237,0.1)',
    colorBorder: 'rgba(0, 0, 0, 0.15)',
    boxShadowSecondary: '0px 0px 3px 1px rgba(0,162,255,0.1)',
    paddingXXS: 0,
    borderRadiusSM: 0,
    optionSelectedColor: '#26ABED',
  },
  Slider: {},
  Switch: {},
  Transfer: {},
  TreeSelect: {
    controlItemBgHover: '#26ABED',
    controlItemBgActive: '#008EE0',
    nodeHoverBg: 'transparent',
    nodeSelectedBg: 'transparent',
  },
  Upload: {},
  Avatar: {},
  Badge: {},
  Calendar: {},
  Card: {},
  Carousel: {},
  Collapse: {},
  Descriptions: {},
  Empty: {},
  Image: {},
  List: {},
  Popover: {},
  Segmented: {},
  Statistic: {},
  Table: {},
  Tabs: { borderRadius: 2, borderRadiusLG: 2 },
  Tag: {},
  Timeline: {},
  Tooltip: {},
  Tree: {
    controlItemBgHover: '#26ABED',
    controlItemBgActive: '#008EE0',
    nodeHoverBg: 'transparent',
    nodeSelectedBg: 'transparent',
  },
  Alert: {},
  Drawer: {},
  Message: { boxShadow: '0px 4px 12px 1px rgba(0,0,0,0.09)' },
  Modal: { boxShadow: '0px 4px 12px 1px rgba(0,0,0,0.09)' },
  Notification: { boxShadow: '0px 4px 12px 1px rgba(0,0,0,0.09)' },
  Popconfirm: { boxShadow: '0px 4px 12px 1px rgba(0,0,0,0.09)' },
  Progress: {},
  Result: {},
  Skeleton: {},
  Spin: {},
  Menu: {
    colorFillAlter: 'rgba(0, 0, 0, 0)',
    borderRadius: 0,
    borderRadiusLG: 0,
    borderRadiusSM: 0,
    borderRadiusXS: 0,
    itemMarginInline: 0,
  },
};
